spring:
  application:
    name: trustzero-escrow-engine

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/escrow_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

  fireworks:
    api:
      key: ${FIREWORKS_API_KEY:dummy_key_for_now_will_replace_later}
