spring:
  application:
    name: trustzero-escrow-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/escrow_db
    username: postgres
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update      # Automatically creates/updates your database tables based on your Java code
    show-sql: true          # Prints SQL to your console (crucial for debugging our locks later)
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}               #environment variable mein daala hai. toh vaha se lega yeh.
  expiration: 86400000